### ISSUE TITLE
Weird problem

### ISSUE THREAD

**Issue by ProjektPremium** [david63/autodbbackup#11]
Is there a reason why in the "Logged administrator actions", it's showing random site users backing up the database?

It was doing it under "Anonymous" and now it's picking random usernames. 

https://ibb.co/ypmrkj1
https://ibb.co/Svcwnbs
https://ibb.co/C6S9K7z

**Comment by david63** [comment]
That is normal behaviour.

The username is that of the user that initiates the cron job on your board and can be anyone - Anonymous being any guest, or bot, that happens to access a page at the time that the cron job is due to be run.

**Comment by ProjektPremium** [comment]
Okay, thank you for your response. :)
