### ISSUE TITLE
Error on phpBB 3.3

### ISSUE THREAD

**Issue by tomdeblende** [david63/autodbbackup#2]
When trying to edit settings on phpBB 3.3 I get this error:

The default timzone in your php.ini file is invalid.

**Comment by david63** [comment]
That means exactly what it says - the timezone in php.ini is invalid, probably not set

**Comment by tomdeblende** [comment]
Correct. Weird, as it is set in the phpBB settings, and a php.ini is auto-generated from that.

Thanks for making me feel dumb ;)
