### ISSUE TITLE
date.timezone:	no value

### ISSUE THREAD

**Issue by henshingly** [david63/autodbbackup#7]
I don't have access to the php.ini file.
In this the date.timezone is displayed as no value. Therefore, i cannot make any settings when i call up "Auto database backup settings
![Screenshot_2020-09-22 Information](https://user-images.githubusercontent.com/20314109/93860265-1b962800-fcbf-11ea-9c6e-86be1b5bcad0.png)
".

**Comment by david63** [comment]
I would suggest that you ask your host to set the date.timezone in the php.ini file - it should be set anyway

**Comment by henshingly** [comment]
I wrote to the support of my web host and asked him to change date.timezone = "no value" to date.timezone = "Europe / Berlin". Now everything works, including my German translation.
